Repository NOW-SOPT-APP4-KREAM/KREAM-Android, pull requests merged in 2024-05, with the labels that each got.

#4 [docs] update README.md
  README.md
Labels: 🐸 지현 🐸, 📕 docs 📕

#6 [init] compose 초기 세팅
  .github/pull_request_template.md
  app/build.gradle.kts
  app/src/main/java/org/sopt/kream/theme/Color.kt
  app/src/main/java/org/sopt/kream/theme/Theme.kt
  app/src/main/java/org/sopt/kream/theme/Type.kt
  gradle/libs.versions.toml
Labels: 🐸 지현 🐸, ✨ init ✨

#13 [init] 폰트, 색상 세팅 + 상단바 구현
  .editorconfig
  app/build.gradle.kts
  app/src/main/java/org/sopt/kream/presentation/ui/dummy/DummyActivity.kt
  app/src/main/java/org/sopt/kream/presentation/ui/dummy/View1Screen.kt
  app/src/main/java/org/sopt/kream/theme/Color.kt
  app/src/main/java/org/sopt/kream/theme/Theme.kt
  app/src/main/java/org/sopt/kream/theme/Type.kt
  app/src/main/res/drawable/ic_topappbar_bell_28.xml
  app/src/main/res/values/strings.xml
  build.gradle.kts
  gradle/libs.versions.toml
Labels: 🐻‍❄️ 민석 🐻‍❄️, ✨ init ✨

#15 [init] 아이콘 세팅
  app/src/main/res/drawable/ic_alarm_plus_24.xml
  app/src/main/res/drawable/ic_bar_alarm_28.xml
  app/src/main/res/drawable/ic_bar_back_24.xml
  app/src/main/res/drawable/ic_bar_plus_24.xml
  app/src/main/res/drawable/ic_bar_share_24.xml
  app/src/main/res/drawable/ic_bottom_navi_home_28.xml
  app/src/main/res/drawable/ic_bottom_navi_my_28.xml
  app/src/main/res/drawable/ic_bottom_navi_saved_28.xml
  app/src/main/res/drawable/ic_bottom_navi_shop_28.xml
  app/src/main/res/drawable/ic_bottom_navi_style_28.xml
  app/src/main/res/drawable/ic_card_saved_small_16.xml
  app/src/main/res/drawable/ic_card_style_16.xml
  app/src/main/res/drawable/ic_channel_ch_24.xml
  app/src/main/res/drawable/ic_channel_facebook_24.xml
  app/src/main/res/drawable/ic_channel_instagram_24.xml
  app/src/main/res/drawable/ic_check_12.xml
  app/src/main/res/drawable/ic_delete_24.xml
  app/src/main/res/drawable/ic_delete_black_16.xml
  app/src/main/res/drawable/ic_detail_24.xml
  app/src/main/res/drawable/ic_etc_next_16.xml
  app/src/main/res/drawable/ic_etc_q_16.xml
  app/src/main/res/drawable/ic_etc_sort_16.xml
  app/src/main/res/drawable/ic_etc_toggle_16.xml
  app/src/main/res/drawable/ic_etc_toggle_circle_16.xml
  app/src/main/res/drawable/ic_fd_16.xml
  app/src/main/res/drawable/ic_plus_2_16.xml
  app/src/main/res/drawable/ic_plus_8.xml
  app/src/main/res/drawable/ic_saved_1_off_24.xml
  app/src/main/res/drawable/ic_saved_1_on_24.xml
  app/src/main/res/drawable/ic_saved_2_off_24.xml
  app/src/main/res/drawable/ic_saved_2_on_24.xml
  app/src/main/res/drawable/ic_saved_small_off_16.xml
  app/src/main/res/drawable/ic_saved_small_on_16.xml
  app/src/main/res/drawable/ic_search_dark_24.xml
  app/src/main/res/drawable/ic_search_light_24.xml
  app/src/main/res/drawable/ic_updown_down_8.xml
  app/src/main/res/drawable/ic_updown_up_8.xml
  app/src/main/res/drawable/ic_video_16.xml
  app/src/main/res/drawable/img_deliver_01_38.png
  app/src/main/res/drawable/img_deliver_02_38.png
  app/src/main/res/drawable/img_deliver_03_38.png
Labels: 🐻‍❄️ 민석 🐻‍❄️, ➕ add ➕

#10 [init] Jetpack Navigation 세팅
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/kream/presentation/ui/main/MainActivity.kt
  app/src/main/java/org/sopt/kream/presentation/ui/main/home/recommend/RecommendFragment.kt
  app/src/main/java/org/sopt/kream/presentation/ui/main/home/release/ReleaseFragment.kt
  app/src/main/java/org/sopt/kream/presentation/ui/productdetail/ProductDetailFragment.kt
  app/src/main/java/org/sopt/kream/presentation/ui/search/SearchFragment.kt
  app/src/main/res/color/selector_main_bnv_item_text_color.xml
  app/src/main/res/drawable/ic_bnv_home.xml
  app/src/main/res/drawable/ic_bnv_my.xml
  app/src/main/res/drawable/ic_bnv_saved.xml
  app/src/main/res/drawable/ic_bnv_shop.xml
  app/src/main/res/drawable/ic_bnv_style.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_product_detail.xml
  app/src/main/res/layout/fragment_recommend.xml
  app/src/main/res/layout/fragment_release.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/menu/menu_bnv.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
Labels: 🐶 효빈 🐶, ✨ init ✨

#19 [feat] TabLayout, EditText 생성 및 화면 이동 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/kream/presentation/HomeTabBarType.kt
  app/src/main/java/org/sopt/kream/presentation/ui/dummy/DummyActivity.kt
  app/src/main/java/org/sopt/kream/presentation/ui/dummy/View1Screen.kt
  app/src/main/java/org/sopt/kream/presentation/ui/main/MainActivity.kt
  app/src/main/java/org/sopt/kream/presentation/ui/main/home/HomeFragment.kt
  app/src/main/java/org/sopt/kream/presentation/ui/main/home/recommend/RecommendFragment.kt
  app/src/main/java/org/sopt/kream/theme/Theme.kt
  app/src/main/java/org/sopt/kream/util/component/KreamTabBar.kt
  app/src/main/java/org/sopt/kream/util/component/KreamTextField.kt
  app/src/main/java/org/sopt/kream/util/modifier/ModifierExt.kt
  app/src/main/java/org/sopt/kream/util/view/KreamFragmentStateAdapter.kt
  app/src/main/res/drawable/ic_bnv_home.xml
  app/src/main/res/drawable/ic_bnv_my.xml
  app/src/main/res/drawable/ic_bnv_saved.xml
  app/src/main/res/drawable/ic_bnv_shop.xml
  app/src/main/res/drawable/ic_bnv_style.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/menu/menu_bnv.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
Labels: 🐸 지현 🐸, ⚡️ feat ⚡️

#21 [init] ViewPager indicator 구현
  app/src/main/res/drawable/shape_tab_indicator_rect_2.xml
  app/src/main/res/layout/indicator_tab_kream.xml
Labels: 🐶 효빈 🐶, ✨ init ✨

#25 [feat] 검색 뷰 구현
  app/src/main/java/org/sopt/kream/data/ApiFactory.kt
  app/src/main/java/org/sopt/kream/data/datasource/ProductRemoteDataSource.kt
  app/src/main/java/org/sopt/kream/data/datasourceimpl/ProductRemoteDataSourceImpl.kt
  app/src/main/java/org/sopt/kream/data/mapper/RelateRecommendProductResponseDtoMapper.kt
  app/src/main/java/org/sopt/kream/data/mapper/ResponseSearchProductDtoMapper.kt
  app/src/main/java/org/sopt/kream/data/mapper/SearchFindProductResponseDtoMapper.kt
  app/src/main/java/org/sopt/kream/data/model/response/ResponseSearchProductDto.kt
  app/src/main/java/org/sopt/kream/data/repository/ProductRepositoryImpl.kt
  app/src/main/java/org/sopt/kream/data/service/ProductService.kt
  app/src/main/java/org/sopt/kream/domain/model/RelateRecommendProductModel.kt
  app/src/main/java/org/sopt/kream/domain/model/RelatedSearchWordModel.kt
  app/src/main/java/org/sopt/kream/domain/model/SearchFindProductModel.kt
  app/src/main/java/org/sopt/kream/domain/model/SearchProductModel.kt
  app/src/main/java/org/sopt/kream/domain/repository/ProductRepository.kt
  app/src/main/java/org/sopt/kream/presentation/common/ViewModelFactory.kt
  app/src/main/java/org/sopt/kream/presentation/ui/main/home/HomeFragment.kt
  app/src/main/java/org/sopt/kream/presentation/ui/search/SearchFragment.kt
  app/src/main/java/org/sopt/kream/presentation/ui/search/SearchRelateRecommendProductAdapter.kt
  app/src/main/java/org/sopt/kream/presentation/ui/search/SearchRelateRecommendProductListAdapter.kt
  app/src/main/java/org/sopt/kream/presentation/ui/search/SearchRelateRecommendProductListViewHolder.kt
  app/src/main/java/org/sopt/kream/presentation/ui/search/SearchRelateRecommendProductViewHolder.kt
  app/src/main/java/org/sopt/kream/presentation/ui/search/SearchRelatedSearchWordAdapter.kt
  app/src/main/java/org/sopt/kream/presentation/ui/search/SearchRelatedSearchWordListAdapter.kt
  app/src/main/java/org/sopt/kream/presentation/ui/search/SearchRelatedSearchWordListViewHolder.kt
  app/src/main/java/org/sopt/kream/presentation/ui/search/SearchRelatedSearchWordViewHolder.kt
  app/src/main/java/org/sopt/kream/presentation/ui/search/SearchSearchFindProductAdapter.kt
  app/src/main/java/org/sopt/kream/presentation/ui/search/SearchSearchFindProductListAdapter.kt
  app/src/main/java/org/sopt/kream/presentation/ui/search/SearchSearchFindProductListViewHolder.kt
  app/src/main/java/org/sopt/kream/presentation/ui/search/SearchSearchFindProductViewHolder.kt
  app/src/main/java/org/sopt/kream/presentation/ui/search/SearchTopBarAdapter.kt
  app/src/main/java/org/sopt/kream/presentation/ui/search/SearchTopBarViewHolder.kt
  app/src/main/java/org/sopt/kream/presentation/ui/search/SearchViewModel.kt
  app/src/main/java/org/sopt/kream/presentation/ui/type/HomeTabBarType.kt
  app/src/main/java/org/sopt/kream/presentation/ui/type/SearchTabBarType.kt
  app/src/main/java/org/sopt/kream/util/base/BaseResponse.kt
  app/src/main/java/org/sopt/kream/util/component/KreamTabBar.kt
  app/src/main/res/drawable/ic_search_sorting_16.xml
  app/src/main/res/drawable/shape_border_radius_10.xml
  app/src/main/res/drawable/shape_border_radius_2.xml
  app/src/main/res/drawable/shape_line_gray06_radius_20.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/item_search_relate_recommend_product.xml
  app/src/main/res/layout/item_search_relate_recommend_product_list.xml
  app/src/main/res/layout/item_search_related_search_word.xml
  app/src/main/res/layout/item_search_related_search_word_list.xml
  app/src/main/res/layout/item_search_search_find_product.xml
  app/src/main/res/layout/item_search_search_find_product_list.xml
  app/src/main/res/layout/item_search_top_bar.xml
  app/src/main/res/layout/view_fast_delivery.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  gradle/libs.versions.toml
Labels: 🐸 지현 🐸, ⚡️ feat ⚡️

#23 [feat] 발매정보 뷰 구현
  app/build.gradle.kts
  app/src/main/java/org/sopt/kream/data/model/request/RequestDeleteScrapDto.kt
  app/src/main/java/org/sopt/kream/data/model/response/ResponseDeleteScrapDto.kt
  app/src/main/java/org/sopt/kream/data/model/response/ResponseReleaseProductDto.kt
  app/src/main/java/org/sopt/kream/data/service/ProductService.kt
  app/src/main/java/org/sopt/kream/presentation/ui/main/home/release/AdvertisementDataClass.kt
  app/src/main/java/org/sopt/kream/presentation/ui/main/home/release/ReleaseFragment.kt
  app/src/main/java/org/sopt/kream/presentation/ui/main/home/release/ReleaseProductViewModel.kt
  app/src/main/java/org/sopt/kream/theme/Type.kt
  app/src/main/res/drawable/bg_bar_text_background_gray.xml
  app/src/main/res/drawable/img_view1_ad_01.png
  app/src/main/res/drawable/img_view1_ad_02.png
  app/src/main/res/drawable/img_view1_ad_03.png
  app/src/main/res/drawable/img_view1_ad_04.png
  app/src/main/res/drawable/img_view1_swipe_dummy.png
  app/src/main/res/font/roboto_bold.ttf
  app/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: 🐻‍❄️ 민석 🐻‍❄️, ⚡️ feat ⚡️

#32 [feat] 검색 뷰 상품열 조정 기능 구현
  app/src/main/java/org/sopt/kream/presentation/ui/search/SearchFragment.kt
  app/src/main/java/org/sopt/kream/presentation/ui/search/SearchRelateRecommendProductListAdapter.kt
  app/src/main/java/org/sopt/kream/presentation/ui/search/SearchRelateRecommendProductListViewHolder.kt
  app/src/main/java/org/sopt/kream/presentation/ui/search/SearchRelatedSearchWordListAdapter.kt
  app/src/main/java/org/sopt/kream/presentation/ui/search/SearchRelatedSearchWordListViewHolder.kt
  app/src/main/java/org/sopt/kream/presentation/ui/search/SearchSearchFindProductListAdapter.kt
  app/src/main/java/org/sopt/kream/presentation/ui/search/SearchSearchFindProductListViewHolder.kt
  app/src/main/java/org/sopt/kream/presentation/ui/search/SearchTopBarAdapter.kt
  app/src/main/java/org/sopt/kream/presentation/ui/search/SearchTopBarViewHolder.kt
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/item_search_relate_recommend_product_list.xml
  app/src/main/res/layout/item_search_related_search_word_list.xml
  app/src/main/res/layout/item_search_search_find_product_list.xml
  app/src/main/res/layout/item_search_top_bar.xml
Labels: 🐸 지현 🐸, ⚡️ feat ⚡️

#31 [feat] 스크랩 해제 API 연동
  app/src/main/java/org/sopt/kream/data/datasource/ProductRemoteDataSource.kt
  app/src/main/java/org/sopt/kream/data/datasourceimpl/ProductRemoteDataSourceImpl.kt
  app/src/main/java/org/sopt/kream/data/model/request/RequestDeleteScrapDto.kt
  app/src/main/java/org/sopt/kream/data/model/response/ResponseDeleteScrapDto.kt
  app/src/main/java/org/sopt/kream/data/repository/ProductRepositoryImpl.kt
  app/src/main/java/org/sopt/kream/data/service/ProductService.kt
  app/src/main/java/org/sopt/kream/domain/repository/ProductRepository.kt
  app/src/main/java/org/sopt/kream/presentation/common/ViewModelFactory.kt
  app/src/main/java/org/sopt/kream/presentation/ui/main/home/release/ReleaseFragment.kt
  app/src/main/java/org/sopt/kream/presentation/ui/main/home/release/ReleaseProductViewModel.kt
Labels: 🐻‍❄️ 민석 🐻‍❄️, ⚡️ feat ⚡️

#35 [feat] 화면 연결 및 전체적인 로직 정리
  app/src/main/java/org/sopt/kream/data/datasource/ProductRemoteDataSource.kt
  app/src/main/java/org/sopt/kream/data/datasourceimpl/ProductRemoteDataSourceImpl.kt
  app/src/main/java/org/sopt/kream/data/repository/ProductRepositoryImpl.kt
  app/src/main/java/org/sopt/kream/data/service/ProductService.kt
  app/src/main/java/org/sopt/kream/domain/model/RecommendJustDroppedProductModel.kt
  app/src/main/java/org/sopt/kream/domain/repository/ProductRepository.kt
  app/src/main/java/org/sopt/kream/presentation/common/ViewModelFactory.kt
  app/src/main/java/org/sopt/kream/presentation/ui/main/home/recommend/RecommendAdvertisementViewHolder.kt
  app/src/main/java/org/sopt/kream/presentation/ui/main/home/recommend/RecommendAdvertisementViewPagerAdapter.kt
  app/src/main/java/org/sopt/kream/presentation/ui/main/home/recommend/RecommendCircleMenuAdapter.kt
  app/src/main/java/org/sopt/kream/presentation/ui/main/home/recommend/RecommendForYouAdapter.kt
  app/src/main/java/org/sopt/kream/presentation/ui/main/home/recommend/RecommendForYouViewHolder.kt
  app/src/main/java/org/sopt/kream/presentation/ui/main/home/recommend/RecommendForYouViewPagerAdapter.kt
  app/src/main/java/org/sopt/kream/presentation/ui/main/home/recommend/RecommendFragment.kt
  app/src/main/java/org/sopt/kream/presentation/ui/main/home/recommend/RecommendJustDroppedAdapter.kt
  app/src/main/java/org/sopt/kream/presentation/ui/main/home/recommend/RecommendJustDroppedViewHolder.kt
  app/src/main/java/org/sopt/kream/presentation/ui/main/home/recommend/RecommendViewModel.kt
  app/src/main/java/org/sopt/kream/presentation/ui/main/home/release/ReleaseAdvertisementViewPager.kt
  app/src/main/java/org/sopt/kream/presentation/ui/main/home/release/ReleaseFragment.kt
  app/src/main/java/org/sopt/kream/presentation/ui/main/home/release/ReleaseMiddleChips.kt
  app/src/main/java/org/sopt/kream/presentation/ui/main/home/release/ReleaseProductViewModel.kt
  app/src/main/java/org/sopt/kream/presentation/ui/model/Advertisement.kt
  app/src/main/java/org/sopt/kream/presentation/ui/productdetail/ProductDetailFragment.kt
  app/src/main/java/org/sopt/kream/presentation/ui/productdetail/ProductDetailViewModel.kt
  app/src/main/java/org/sopt/kream/presentation/ui/type/AdvertisementType.kt
  app/src/main/java/org/sopt/kream/util/ExtensionUtils.kt
  app/src/main/java/org/sopt/kream/util/base/NullableBaseResponse.kt
  app/src/main/res/layout/fragment_recommend.xml
  app/src/main/res/layout/item_recommend_circle_menu.xml
  app/src/main/res/layout/item_recommend_for_you.xml
  app/src/main/res/layout/item_recommend_for_you_product.xml
  app/src/main/res/layout/item_recommend_just_dropped_product.xml
  app/src/main/res/layout/view_fast_delivery.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
Labels: 🐸 지현 🐸, ⚡️ feat ⚡️

#44 [chore] 서버 싱크 맞추기
  app/src/main/java/org/sopt/kream/presentation/ui/main/home/recommend/RecommendFragment.kt
  app/src/main/java/org/sopt/kream/presentation/ui/main/home/release/ReleaseFragment.kt
Labels: 🐻‍❄️ 민석 🐻‍❄️, 🪄 chore 🪄

#45 [docs] update README.MD
  README.md
  app/src/main/java/org/sopt/kream/data/ApiFactory.kt
  app/src/main/java/org/sopt/kream/data/datasource/DummyRemoteDataSource.kt
  app/src/main/java/org/sopt/kream/data/datasourceimpl/DummyRemoteDataSourceImpl.kt
  app/src/main/java/org/sopt/kream/data/model/request/RequestDummyDto.kt
  app/src/main/java/org/sopt/kream/data/model/response/ResponseGetDummyUserListDto.kt
  app/src/main/java/org/sopt/kream/data/repository/DummyRepositoryImpl.kt
  app/src/main/java/org/sopt/kream/data/service/DummyService.kt
  app/src/main/java/org/sopt/kream/domain/model/DummyEntity.kt
  app/src/main/java/org/sopt/kream/domain/repository/DummyRepository.kt
  app/src/main/java/org/sopt/kream/presentation/common/ViewModelFactory.kt
  app/src/main/java/org/sopt/kream/presentation/model/Advertisement.kt
  app/src/main/java/org/sopt/kream/presentation/model/ProductDetailInfo.kt
  app/src/main/java/org/sopt/kream/presentation/type/AdvertisementType.kt
  app/src/main/java/org/sopt/kream/presentation/type/HomeTabBarType.kt
  app/src/main/java/org/sopt/kream/presentation/type/ProductDetailButtonType.kt
  app/src/main/java/org/sopt/kream/presentation/type/ProductDetailInfoType.kt
  app/src/main/java/org/sopt/kream/presentation/type/RecommendAdvertisementType.kt
  app/src/main/java/org/sopt/kream/presentation/type/RecommendCircleMenuType.kt
  app/src/main/java/org/sopt/kream/presentation/type/SearchTabBarType.kt
  app/src/main/java/org/sopt/kream/presentation/ui/dummy/DummyActivity.kt
  app/src/main/java/org/sopt/kream/presentation/ui/dummy/DummyViewModel.kt
  app/src/main/java/org/sopt/kream/presentation/ui/main/home/HomeFragment.kt
  app/src/main/java/org/sopt/kream/presentation/ui/main/home/recommend/RecommendCircleMenuAdapter.kt
  app/src/main/java/org/sopt/kream/presentation/ui/main/home/recommend/RecommendCircleMenuViewHolder.kt
  app/src/main/java/org/sopt/kream/presentation/ui/main/home/recommend/RecommendFragment.kt
  app/src/main/java/org/sopt/kream/presentation/ui/main/home/release/ReleaseAdvertisementViewPager.kt
  app/src/main/java/org/sopt/kream/presentation/ui/main/home/release/ReleaseFragment.kt
  app/src/main/java/org/sopt/kream/presentation/ui/main/home/release/ReleaseProductViewModel.kt
  app/src/main/java/org/sopt/kream/presentation/ui/productdetail/ProductDetailFragment.kt
  app/src/main/java/org/sopt/kream/presentation/ui/productdetail/ProductDetailInfoAdapter.kt
  app/src/main/java/org/sopt/kream/presentation/ui/productdetail/ProductDetailInfoViewHolder.kt
  app/src/main/java/org/sopt/kream/presentation/ui/search/SearchFragment.kt
  app/src/main/java/org/sopt/kream/util/component/KreamProductDetailButton.kt
  app/src/main/res/drawable/img_view2_cricle_01.png
  app/src/main/res/drawable/img_view2_cricle_02.png
  app/src/main/res/drawable/img_view2_cricle_03.png
  app/src/main/res/drawable/img_view2_cricle_04.png
  app/src/main/res/drawable/img_view2_cricle_05.png
  app/src/main/res/drawable/img_view2_cricle_06.png
  app/src/main/res/drawable/img_view2_cricle_07.png
  app/src/main/res/drawable/img_view2_cricle_08.png
  app/src/main/res/drawable/img_view2_cricle_09.png
  app/src/main/res/drawable/img_view2_cricle_10.png
Labels: 🐸 지현 🐸, 📕 docs 📕
